title: 'yibudak &#124; ceng student'
description: "Personal Blog of Yiğit Budak"

author:
  name: "İSMAİL YILDIRIM"
  email: "iso.yldrm74@gmail.com"
  url: "https://yldrm25.github.io"

baseurl: /

source: .
destination: ./_site
lang: en
languages: ["en", "tr"]
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "ismailyildirim"
year : "2020"
